# Generated by Django 3.2.9 on 2022-04-01 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220221_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='user',
        ),
        migrations.AlterField(
            model_name='moderatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mod_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pob',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Place-Of-Birth'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
    ]
