# Generated by Django 3.2.9 on 2022-04-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_document_education_employment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='employment',
            options={'ordering': ['-created_at']},
        ),
    ]
