# Generated by Django 3.2.9 on 2022-04-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220221_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-created_at']},
        ),
    ]
