# Generated by Django 3.2.9 on 2022-02-07 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('lms', '0001_initial'),
        ('cms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='attendees',
            field=models.ManyToManyField(through='lms.Enrollment', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='training',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='home.course'),
        ),
        migrations.AddField(
            model_name='training',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='quiz',
            field=models.ManyToManyField(blank=True, to='cms.Quiz'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.training'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'training')},
        ),
    ]
