# Generated by Django 3.2.9 on 2022-02-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='attendee_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='join_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='training',
            name='chime_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
