# Generated by Django 3.2.9 on 2022-02-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20220215_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='permission',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PRIMARY', 'Primary Trainer'), ('OTHER', 'Other Trainer'), ('TRAINEE', 'Trainee'), ('OBSERVER', 'Observer')], max_length=15),
        ),
    ]
